### ISSUE TITLE
Remove master branch, create new merge candidate

### ISSUE THREAD

**Issue by dsolovay** [dsolovay/Sitecore-Instance-Manager#30]
When functionality is locked down and working well, I will create a new merge candidate that is rebased down to one or two commits with detailed commit messages, and open a Pull Request to the main repo.  I will also close the issues that are done on the develop branch. 
The new branch will be called "solr-install".

@AlenPelin, does that make sense?

**Comment by AlenPelin** [comment]
@dsolovay it makes sense.

**Comment by dsolovay** [comment]
master deleted. I will open a PR when I have a decent merge candidate.
