### ISSUE TITLE
Merge in current state of sitecore master fork

### ISSUE THREAD

**Issue by dsolovay** [dsolovay/Sitecore-Instance-Manager#31]

**Comment by dsolovay** [comment]
Meged in sitecore/develop, as this had the latest activity. Working to resolve merge issues before pushing.

**Comment by dsolovay** [comment]
The following code block in ConfigurationActions.cs has been removed, as part of a large refactor commit (https://github.com/Sitecore/Sitecore-Instance-Manager/commit/43ddaf295f33263c4a7756ba8665c92825fb0df8)

```
          case "custom":
            {
              var typeName = action.GetAttribute("type").EmptyToNull().IsNotNull("The type attribute is missing in the <custom> install action");
              var obj = (IPackageInstallActions)ReflectionUtil.CreateObject(typeName);
              obj.Execute(instance, module);
              break;
            }
```

The custom element is required by the following two classes in my process:
- src/SIM.Pipelines/Install/Modules/CreateSolrCore.cs
- src/SIM.Pipelines/Install/Modules/SwitchConfigsToSolr.cs

I can either:
1. Reintroduce the `custom` element and `IPackageInstallActions` or 
2.  Move the logic to new elements `create-solr-cores`, `swtich-configs-to-solr`, that are defined explicitly in ConfigurationActions.cs

I lean to option 1, because I like this extensibility feature, but need @AlenPelin's guidance here.

**Comment by dsolovay** [comment]
Reopening this, as solution does not compile.

**Comment by dsolovay** [comment]
I've went with option 1 above. @AlenPelin please advise if you'd like me to change this.

**Comment by AlenPelin** [comment]
Option 1 is fine.

**Comment by dsolovay** [comment]
Cool. Working to get you a merge candidate tonight.
