### ISSUE TITLE
Solr option does not dispose of ContentSearch.dll, preventing site deletion

### ISSUE THREAD

**Issue by dsolovay** [dsolovay/Sitecore-Instance-Manager#39]
If you try to delete a site in the same session that you've created it, you will receive the following error:
![image](https://cloud.githubusercontent.com/assets/689532/19422940/3dd71ea8-93e9-11e6-9e7f-d6accc177d0e.png)

This is most likey because the GenerateSchema method does not dispose of the SchemaGenerator object. https://github.com/dsolovay/Sitecore-Instance-Manager/blob/515d946754ce32bb6b225d4c920c0152e3cbced8/src/SIM.Pipelines/Install/Modules/CreateSolrCores.cs#L162

**Comment by AlenPelin** [comment]
I could suggest to read assembly bytes to memory stream and then load assembly from memory stream. @dsolovay what do you think?

**Comment by dsolovay** [comment]
I'm going to try to resolve with Application Domains (see http://stackoverflow.com/a/28633417/402949) first.

**Comment by dsolovay** [comment]
Cannot access SchemaGenerator class accross AppDomain because it is not serializable: 

![image](https://cloud.githubusercontent.com/assets/689532/19838503/e8afb4c6-9ea6-11e6-872b-ab759709e70b.png)

**Comment by dsolovay** [comment]
Using this for loading assembly from memory: http://stackoverflow.com/a/20080196/402949

**Comment by dsolovay** [comment]
Initial fix working, but needs to be refactored to follow Util class patterns. See cca62caddf2582572f843ce70afbf446d455f244

**Comment by dsolovay** [comment]
Pull request opened, so closing this issue.
